### ISSUE TITLE
Improve reusability of pre-processing functions

### ISSUE THREAD

**Issue by trevorb1** [DeltaE/Canada-U.S.-ElecTrade#63]
In `dataSources/` there are three files that end with `AUTO_GENERATED.csv`. These are intermediate files created by some scripts that do a fair bit of data processing (such as calculating weighted demand profiles or calculating hourly loads with time zones taken into account). The file is written out because the data in it is read in by another script for further processing. (ie. 2+ scripts need data for weighted demand profiles, and instead of copying functions from one script to another, I just wrote out the data to be read in by the second script)

The more elegant way of handling this problem is creating a helper python file to hold reusable functions that multiple  scripts can pull from (I think). Doing this will also remove the dependency of downstream scripts on the script that writes out the AUTO_GENERATED file. 

Lets look at removing the AUTO_GENERATED files and replacing them with shareable functions in a helper python file.

**Comment by tniet** [comment]
Hey @trevorb1 - two thoughts:
1. Yes, put functions in a header file so they can be re-used/re-purposed.
2. You may still want to create the AUTO_GEN files if that's more computationally efficient than re-running the functions in each script.  It'll depend on the scale of stuff each function does and file reading/writing that's being done and if it's faster to process twice or faster to write out and then read twice.
3. csv's are slow for read/write so for intermediate files used by python a different format might significantly faster.
